CREATE TABLE ACCOUNT (
    ACCOUNT_ID VARCHAR2(18) NOT NULL,
    ACCOUNT_NAME VARCHAR(35) NOT NULL,
    ACCOUNT_BALANCE NUMBER(18,2) DEFAULT 0 NOT NULL,
    ACCOUNT_EMAIL VARCHAR2(64) NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT ACCOUNT_EMAIL_UQ UNIQUE (ACCOUNT_EMAIL)
);

INSERT INTO MICROSERVICES.ACCOUNT
(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_EMAIL)
VALUES('John.Doe', 'Ernest Hemingway', 10000 , 'ernest.hemingway@gmail.com');


INSERT INTO MICROSERVICES.ACCOUNT
(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_BALANCE, ACCOUNT_EMAIL)
VALUES('Marty.McFly', 'Steven Spielberg', 10000 , 'steven.spielverg@gmail.com');

ALTER TABLE ACCOUNT ADD VERSION NUMBER DEFAULT 0 NOT NULL;


UPDATE ACCOUNT SET ACCOUNT_BALANCE = 100;